<a href="https://colab.research.google.com/github/Justmove08/Lesson_1/blob/master/%D0%90%D0%BF%D1%80%D0%B5%D0%BB%D1%8C%D1%81%D0%BA%D0%B8%D0%B9_%D0%BA%D1%83%D1%80%D1%81_2020_Light_Python_%D0%94%D0%BE%D0%BC%D0%B0%D1%88%D0%BD%D0%B5%D0%B5_%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Нейронные сети

## Домашнее задание 2. Numpy и функции

# Light

### Задача 1

1. Подгрузите файл **train_vector_1.csv** с помощью функции **np.loadtxt**. 

2. Назовите подгруженный массив my_array.

3. Убедитесь, что подгруженный массив имеет тип np.ndarray (выведите тип переменной my_array).

Ссылка на файл: https://drive.google.com/open?id=1ngnrhmoMInequrA6JyAe90lEPhcbi0iH

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import numpy as np
my_array = np.loadtxt('/content/drive/My Drive/NeuralUniversity/iris.csv', delimiter=',', skiprows=1)
print('Подгруженный массив имеет тип:',type(my_array))

Подгруженный массив имеет тип: <class 'numpy.ndarray'>


### Задача 2

Напишите код, который считает среднее значение всех элементов массива (без использования встроенных функций np.mean и т.д.). Для решения задачи воспользуйтесь циклом.
* С помощью команды %%timeit отобразите время выполнения написанного кода.
* Преобразуйте массив my_array в список (с помощью метода list()), сохраните его в переменной my_list.
* В новой ячейке посчитайте среднее значение всех элементов списка (воспользуйтесь тем же самым кодом, что и для массива).
* Командой %%timeit отобразите время выполнения и этой ячейки.

In [0]:
# Решение №1. С помощью циклов и массива
import numpy as np
my_array = np.loadtxt(('/content/drive/My Drive/NeuralUniversity/iris.csv'), delimiter=',', skiprows=1)
column_counter = -1 # Счетчик колонок
element_counter_1 = 0 # Счетчик количества элеменов
sum_1 = 0 # Сохранение суммы для последующего вычисления среднего значения
for temp_value_1 in my_array[0]: # При помощи temp_value_1 отслеживаем количество колонок в массиве
    column_counter = column_counter + 1
    for temp_value_2 in my_array[:,column_counter]: # temp_value_2 записывает значение каждого элемента в столбце и суммирует в переменную sum
        sum_1 = temp_value_2 + sum_1
        element_counter_1 = element_counter_1 + 1
answer_1 = sum_1 / element_counter_1
print('Среднее значение всех элементов массива равно (вычислено при помощи циклов): ', answer_1) # Вычисляем среднее арифметическое путем деления суммы всех элементов на их количество
print('Проверяем себя при помощи метода .mean:', my_array.mean())

Среднее значение всех элементов массива равно (вычислено при помощи циклов):  17.671599999999998
Проверяем себя при помощи метода .mean: 17.671599999999998


In [0]:
%%timeit
answer_1

100000000 loops, best of 3: 17.8 ns per loop


In [0]:
# Решение №1. С помощью циклов и массива для файла train_vector_1.csv
import numpy as np
my_array = np.loadtxt('/content/drive/My Drive/NeuralUniversity/train_vector_1.csv')
sum = 0
counter = 0
for i in my_array:
  sum = i + sum
  counter = counter + 1
average_value = sum / counter
print('Среднее значение всех элементов массива (my_array) составляет:', average_value)

Среднее значение всех элементов массива (my_array) составляет: 3.057333333333334


In [0]:
%%timeit
my_array = np.loadtxt('/content/drive/My Drive/NeuralUniversity/train_vector_1.csv')
sum = 0
counter = 0
for i in my_array:
  sum = i + sum
  counter = counter + 1
average_value = sum / counter

1000 loops, best of 3: 1.64 ms per loop


In [0]:
# Решение №2. При помощи списка и циклов
import numpy as np
my_array = np.loadtxt(('/content/drive/My Drive/NeuralUniversity/iris.csv'), delimiter=',', skiprows=1)
my_list = list(my_array)
array_counter = 0
element_counter_2 = 0
sum_2 = 0
for i in my_list:
    element_in_list_counter = 0
    for z in my_list[array_counter]:
        sum_2 = z + sum_2
        element_in_list_counter = element_in_list_counter + 1
        element_counter_2 = element_counter_2 + 1
    array_counter = array_counter + 1
answer_2 = sum_2 / element_counter_2
print('Среднее значение элементов списка (my_list) составляет:', sum_2 / element_counter_2)

Среднее значение элементов списка (my_list) составляет: 17.6716


In [0]:
%%timeit
answer_2

10000000 loops, best of 3: 21.8 ns per loop


In [0]:
# Решение №2. При помощи списка и циклов для файла train_vector_1.csv
import numpy as np

In [0]:
my_array = np.loadtxt('/content/drive/My Drive/NeuralUniversity/train_vector_1.csv')
my_list = list(my_array)
sum = 0
count = 0
for i in my_list:
  sum = sum + i
  count = count + 1
average_value = sum / count
print('Среднее значение элементов списка (my_list) составляет:', average_value)

3.057333333333334


In [0]:
%%timeit
my_array = np.loadtxt('/content/drive/My Drive/NeuralUniversity/train_vector_1.csv')
my_list = list(my_array)
sum = 0
count = 0
for i in my_list:
  sum = sum + i
  count = count + 1
average_value = sum / count

1000 loops, best of 3: 1.63 ms per loop


### Задача 3

Подгрузите файл **iris.csv** с помощью встроенной функции **np.loadtxt**. Назовите его my_2d_array. Напиишите код, который считает сумму элементов массива по столбцам (для решения данной задачи воспользуйтесь разделом ноутбук "Операции с двумерными массивами и встроенные методы").

In [0]:
import numpy as np
my_2d_array = np.loadtxt(('/content/drive/My Drive/NeuralUniversity/iris.csv'), delimiter=',', skiprows=1)
sum = my_2d_array.sum(axis = 0)
print(sum)

[11175.    876.5   458.6   563.7   179.9]


### Задача 4 

* Используя библиотеку numpy, создайте массив 3x3, значения которого находятся в диапазоне от 11 до 40 (раздел "Семплирование из распределений"). 

* Не используя цикл for,  выведите на экран список элементов, которые меньше 20 (раздел "Индексация").

* Просуммируйте все элементы, не используя цикл for (раздел "Встроенные методы").


In [0]:
import numpy as np
i = np.random.randint(11,41,(3,3))
b = i[i < 20]
print('Элементы массива, значения которых меньше 20:', i[i < 20])
print('Сумма всех элементов массива, значения которых меньше 20: ', b.sum())
print('Сумма всех элементов массива составляет: ', i.sum())

Элементы массива, значения которых меньше 20: [13 14]
Сумма всех элементов массива, значения которых меньше 20:  27
Сумма всех элементов массива составляет:  226


### Задача 5

* Создайте массив, который будет содержать списки с именем студента(str), его возрастом(int) и средней оценкой(float) (обратите внимание на пример с занятия со списком автомобильных регионов).
* Отсортируйте такой массив (обратите внимание на параметр order метода sort()).
* Замените значение, отвечающее за возраст, у всех студентов на одно и то же, например, 10. Отсортируйте такой массив. 

In [0]:
import numpy as np
my_type = [('Имя студента', '<U32'), ('Возраст', np.int32), ('Средняя оценка', np.float64)]
values = [('Алексей', 23, 4.5),('Николай', 19, 5.5),('Дарья', 18, 2.5)]
students = np.array(values, dtype = my_type)

print('Исходное состояние массива: ', students)

name_sort = np.sort(students, order = 'Имя студента')
print('Сортировка элементов массива по имени: ', name_sort)

age_sort = np.sort(students, order = 'Возраст')
print('Сортировка элементов массива по возрасту: ', age_sort)

point_sort = np.sort(students, order = 'Средняя оценка')
print('Сортировка элементов массива по средней оценке: ', point_sort)

students['Возраст'] = 10
var_10 = np.sort(students)
print('Замена значений возраста у всех студентов на 10: ', var_10)


Исходное состояние массива:  [('Алексей', 23, 4.5) ('Николай', 19, 5.5) ('Дарья', 18, 2.5)]
Сортировка элементов массива по имени:  [('Алексей', 23, 4.5) ('Дарья', 18, 2.5) ('Николай', 19, 5.5)]
Сортировка элементов массива по возрасту:  [('Дарья', 18, 2.5) ('Николай', 19, 5.5) ('Алексей', 23, 4.5)]
Сортировка элементов массива по средней оценке:  [('Дарья', 18, 2.5) ('Алексей', 23, 4.5) ('Николай', 19, 5.5)]
Замена значений возраста у всех студентов на 10:  [('Алексей', 10, 4.5) ('Дарья', 10, 2.5) ('Николай', 10, 5.5)]


## Pro версия

### Задача 1

* Подгрузите массив **iris.csv** и назовите его my_array. 

* Создайте двумерный массив из случайных чисел той же размерности, что и my_array (раздел "Семплирование из распределений", потребуется использовать размерность массива my_array).

* Назовите его my_generated_array.

In [0]:
import numpy as np
my_array = np.loadtxt('/content/drive/My Drive/NeuralUniversity/iris.csv', delimiter =  ',', skiprows = 1)
my_generated_array = np.random.randint(1,100,(150,5))
print(my_generated_array)
print('\nПроверка на соответствие условию о создании массива той же размерности: ')
print('Размерность массива "my_array": ', my_array.shape)
print('Количество элементов в массиве "my_array": ', my_array.size)
print('Размерность массива "my_generated_array": ', my_generated_array.shape)
print('Количество элементов в массиве "my_generated_array": ', my_generated_array.size)

[[48 97 28 31 97]
 [59 43 37 69 97]
 [22 39 12 31 33]
 [61 30 58 96 42]
 [69 56 41 72 20]
 [27 25 77 40 61]
 [17 19  6 89  6]
 [37 11 50 18 13]
 [45 54 30 72 59]
 [88 62 81 57 11]
 [89 28 19 47 87]
 [48 64 23 75 29]
 [93 17 37 90  1]
 [48 24 23 53 25]
 [67 99 79 70 78]
 [91 21 75 16 65]
 [16 44 50 44 54]
 [77 35 73 87 40]
 [16 44 92 78 86]
 [58 32 68 44 13]
 [68 65 91 54 35]
 [69 43  1 26 74]
 [53 55 38 17 51]
 [36 39 18 22  7]
 [25 98 25 23 84]
 [93 86 96 27 70]
 [93 94 25 36 14]
 [77 70 84  2 61]
 [ 2 79  6 62 94]
 [72 13 69 59 43]
 [83 29 61 69 86]
 [48 44  7 42 92]
 [17  6 95 35 94]
 [38 94 78  6 64]
 [38  9 65 61 63]
 [99 23 19 87 90]
 [71 31 91 41  3]
 [95 93 67 63 24]
 [85 11 60  6 42]
 [88 53 92 59 43]
 [84  7  2 64 53]
 [28 40  9 16 22]
 [98 61 75 22 60]
 [68 72 59 10 10]
 [33 29 25 48 29]
 [93 88 28 81 18]
 [47 10 65 82 85]
 [13 30 31 20 92]
 [37 21  6 95 47]
 [13 13 94  6 19]
 [17 58 34 93 35]
 [79 66 16 75 42]
 [ 6 73 56 79 79]
 [71 85 31 36 46]
 [11 61 21 55 41]
 [ 6 22 35

### Задача 2

* Выполните поэлементное умножение my_array на my_generated_array (раздел "векторные операции").

* Склейте массивы my_array, my_generated_array в один (могут помочь методы np.concatenate, np.vstack, np.hstack).

* Возьмите склеенный массив и разделите его на равные части (больше двух). Можно сделать вручную через циклы либо воспользоваться методом vsplit.

In [53]:
import numpy as np
my_array = np.loadtxt('/content/drive/My Drive/NeuralUniversity/iris.csv', delimiter =  ',', skiprows = 1)
my_generated_array = np.random.randint(1,100,(150,5))

# Вывод информации о массивах
print('Инофмация о массиве "my_array":')
print('Размерность: ', my_array.shape)
print('Количество элементов: ', my_array.size)

print('\nИнофмация о массиве "my_generated_array":')
print('Размерность: ', my_generated_array.shape)
print('Количество элементов: ', my_generated_array.size)

# Поэлементное умножение my_array на my_generated_array
prod_array = my_array * my_generated_array

# Склеивание массива my_array c my_generated_array в один массив concatenate_array
concatenate_array = np.concatenate((my_array, my_generated_array))
print('\nИнофмация о склееном массиве "concatenate_array":')
print('Размерность: ', concatenate_array.shape)
print('Количество элементов: ', concatenate_array.size)

# Разделение concatenate_array на 3 части при помощи метода .vsplit
split_array = np.vsplit(concatenate_array, 3)

Инофмация о массиве "my_array":
Размерность:  (150, 5)
Количество элементов:  750

Инофмация о массиве "my_generated_array":
Размерность:  (150, 5)
Количество элементов:  750

Инофмация о склееном массиве "concatenate_array":
Размерность:  (300, 5)
Количество элементов:  1500


In [57]:
'''
Решение разделения NumPy массива на равное количество частей при помощи цикла. Количество частей определяет пользователь
Для работы кода необходимо запустить предыдущую ячейку
'''
part = int(input('Введите количество частей, на которые необходимо разделить NymPy массив: '))
n1 = 0
n2 = int((concatenate_array.shape[0] / part) + 1)
cycle_splited_list = []
for i in range(part):
    part_array = concatenate_array[n1:n2,:]
    cycle_splited_list.append(part_array)
    n1 = n2
    n2 = n2 + int((concatenate_array.shape[0] / part))
cycle_splited_array = np.array(cycle_splited_list)
print(cycle_splited_array)
print('\nКоличество равных NumPy массивов в NumPy массиве составляет:', cycle_splited_array.size)

Введите количество частей, на которые необходимо разделить NymPy массив: 3
[array([[  0. ,   5.1,   3.5,   1.4,   0.2],
       [  1. ,   4.9,   3. ,   1.4,   0.2],
       [  2. ,   4.7,   3.2,   1.3,   0.2],
       [  3. ,   4.6,   3.1,   1.5,   0.2],
       [  4. ,   5. ,   3.6,   1.4,   0.2],
       [  5. ,   5.4,   3.9,   1.7,   0.4],
       [  6. ,   4.6,   3.4,   1.4,   0.3],
       [  7. ,   5. ,   3.4,   1.5,   0.2],
       [  8. ,   4.4,   2.9,   1.4,   0.2],
       [  9. ,   4.9,   3.1,   1.5,   0.1],
       [ 10. ,   5.4,   3.7,   1.5,   0.2],
       [ 11. ,   4.8,   3.4,   1.6,   0.2],
       [ 12. ,   4.8,   3. ,   1.4,   0.1],
       [ 13. ,   4.3,   3. ,   1.1,   0.1],
       [ 14. ,   5.8,   4. ,   1.2,   0.2],
       [ 15. ,   5.7,   4.4,   1.5,   0.4],
       [ 16. ,   5.4,   3.9,   1.3,   0.4],
       [ 17. ,   5.1,   3.5,   1.4,   0.3],
       [ 18. ,   5.7,   3.8,   1.7,   0.3],
       [ 19. ,   5.1,   3.8,   1.5,   0.3],
       [ 20. ,   5.4,   3.4,   1.7,   0.2],


### Задача 3

* Найдите все элементы массива my_array, которые больше трех и меньше 5 одновременно. Используйте методологию подвыборки массива с условием (раздел "Индексация").

In [0]:
import numpy as np
my_array = np.loadtxt('/content/drive/My Drive/NeuralUniversity/iris.csv', delimiter =  ',', skiprows = 1)
print(my_array[(my_array > 3) & (my_array < 5)])

# Если вместо & поставить and, то код не сработает

[3.5 4.9 4.7 3.2 4.6 3.1 4.  3.6 3.9 4.6 3.4 3.4 4.4 4.9 3.1 3.7 4.8 3.4
 4.8 4.3 4.  4.4 3.9 3.5 3.8 3.8 3.4 3.7 4.6 3.6 3.3 4.8 3.4 3.4 3.5 3.4
 4.7 3.2 4.8 3.1 3.4 4.1 4.2 4.9 3.1 3.2 3.5 4.9 3.6 4.4 3.4 3.5 4.5 4.4
 3.2 3.5 3.8 4.8 3.8 4.6 3.2 3.7 3.3 3.2 4.7 3.2 4.5 3.1 4.9 4.  4.6 4.5
 3.3 4.7 4.9 3.3 4.6 3.9 3.5 4.2 4.  4.7 3.6 3.1 4.4 4.5 4.1 4.5 3.9 3.2
 4.8 4.  4.9 4.7 4.3 4.4 4.8 4.5 3.5 3.8 3.7 3.9 4.5 3.4 4.5 3.1 4.7 4.4
 4.1 4.  4.4 4.6 4.  3.3 4.2 4.2 4.2 4.3 4.1 3.3 4.9 4.5 3.6 3.2 3.2 3.8
 3.2 4.9 4.9 3.3 3.2 4.8 4.9 3.8 3.4 3.1 4.8 3.1 3.1 3.1 3.2 3.3 3.4]


### Задача 4

Создайте трехмерный массив размера 2 на 3 на 4, состоящий из случайных ВЕЩЕСТВЕННЫХ чисел от 15 до 37. Используйте встроенные методы библиотеки  np.random.

In [0]:
import numpy as np
# Гугл подсказал такую формулу "(b - a) * random(...) + a"
array_3d = ((38 - 15) * np.random.random(size = (4,2,3)) + 15)
print(array_3d)

[[[23.10305936 16.41917673 16.10099907]
  [21.15148773 25.55122265 24.68847894]]

 [[36.9936518  23.58577606 19.11318672]
  [33.25510363 29.48866167 15.04791254]]

 [[23.39979657 27.99653775 16.20443602]
  [25.21848213 35.06579569 16.49301175]]

 [[24.58631298 30.41094695 22.08204676]
  [35.60225304 18.24889779 22.41541683]]]


### Задача 5

Используя массив из предыдущей задачи, преобразуйте его в новый массив со следующими значениями:

    * "small", если значения меньше 20
    * "medium", если значения в промежутке [20, 30]
    * "large", если значения больше 30

In [0]:
import numpy as np

array_3d = ((38 - 15) * np.random.random(size = (4,2,3)) + 15)

# Маски для фильтрации элементов
small_mask = array_3d < 20
medium_mask = (array_3d >= 20) & (array_3d <=30)
large_mask = array_3d > 30

# Замена найденных элементов специальным значением
array_3d[small_mask] = 1.111112222233333
array_3d[medium_mask] = 2.222223333344444
array_3d[large_mask] = 3.333334444455555

# Замена специальных значений на 'small', 'medium', 'large'
new_array = array_3d.astype('<U32')
new_array[new_array == '1.111112222233333'] = 'small'
new_array[new_array == '2.222223333344444'] = 'medium'
new_array[new_array == '3.333334444455555'] = 'large'

print(new_array)

[[['small' 'medium' 'large']
  ['medium' 'large' 'large']]

 [['large' 'small' 'small']
  ['large' 'medium' 'large']]

 [['large' 'medium' 'large']
  ['large' 'large' 'large']]

 [['small' 'small' 'small']
  ['small' 'large' 'medium']]]


### Задача 6

Создайте одномерный массив из случайных 10 значений. 

* Не используя цикл for, найдите сумму значений с 3 по 7 элемент.
* Найдите сумму квадратов последних двух элементов.

In [0]:
import numpy as np

i = np.random.randint(30,50,10)
print(i)
print('Значения с 3 по 7 элемент: ', i[2:7])
print('Сумма значений с 3 по 7 элемент:', i[2:7].sum())
print('Последние 2 элемента: ', i[-2:])
print('Сумма квадратов последний 2-ух элементов:', (i[-1] ** 2) + (i[-2] ** 2))

[37 48 38 34 43 36 35 48 33 44]
Значения с 3 по 7 элемент:  [38 34 43 36 35]
Сумма значений с 3 по 7 элемент: 186
Последние 2 элемента:  [33 44]
Сумма квадратов последний 2-ух элементов: 3025
